# File introduces automated checks triggered on git events
# to enable run `pip install pre-commit && pre-commit install`

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-json
        exclude: |
          (?x)^(
                  ^tests/data/json/ill_formed.json
              )$
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-yaml
        exclude: |
          (?x)^(
                  ^conda.recipe/meta.yaml
              )$
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: sort-simple-yaml
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        args: ['--line-length=119']
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    - id: flake8
      exclude: |
        (?x)^(
                ^docs/conf.py
            )$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
    - id: yamllint
    name: yamllint
    description: This hook runs yamllint.
    entry: yamllint
    language: python
    types: [file, yaml]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.1
    hooks:
    - id: nbstripout
