version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      - mkdir ~/tmp
    post_install:
      - conda install -c conda-forge glibc=2.32

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: environment.yml
