version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    pre_build:
      - mkdir ~/tmp

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

conda:
  environment: environment.yml
