# sudo: false
# # dist: trusty
sudo: required
dist: trusty
group: deprecated-2017Q4

language: python

cache:
  directories:
    - $HOME/mc

python:
   - 3.6

branches:
        #  only:
        #    - master
#
# services:
#
# matrix:
#  include:
#    - os: linux

env:

before_install:
  - rm -rf /home/travis/mc  # forcing cache creation
  - if [ -d /home/travis/mc ] ; then export USE_CACHE=yes; echo "Use cache"; else export USE_CACHE=no; fi
  - ./builders/travis/before_install.sh
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - ./builders/travis/install.sh

script:
  - travis_wait 90 ./builders/travis/script.sh

notifications:
  email:
    on_success: change
    on_failure: always
