language: python

python:
  - "2.7"

sudo: false
   
before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.5.5-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.5.5-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
  - export PATH=/home/travis/mc/bin:$PATH

install:
  - export GIT_FULL_HASH=`git rev-parse HEAD`
  - conda config --set always_yes true
  - conda update conda
  - conda create -n testenv
  - conda install nose numpy astropy tomopy python-coveralls
  - source activate testenv
  - python setup.py install

script:
   - nosetests test --with-coverage

after_success:
  - coveralls

notifications:
  email:
    on_success: change
    on_failure: always