name: imars3d
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - astropy
  - tomopy
  - dxchange
  - pooch
  - panel
  - param
  - pyvista
  - holoviews
  - bokeh
  - datashader
  - hvplot
  - build
  - toml
  - black
  - versioningit
  - conda-build
  - pytest
  - pytest-cov
  - pre-commit
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - versioningit
    - check-wheel-contents
