name: imars3d
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy
  - tomopy
  - dxchange
  - jsonschema
  - pooch
  - panel
  - param
  - pyvista
  - holoviews
  - bokeh
  - datashader
  - hvplot
  - build
  - toml
  - pip:
    - versioningit
    - check-wheel-contents
