name: imars3d
channels:
  - conda-forge
dependencies:
  # -- Runtime
  # base
  - python
  - versioningit
  - toml
  # compute
  - astropy
  - tomopy
  - algotom
  - numpy < 2
  # plot
  - holoviews
  - bokeh
  - datashader
  - hvplot
  # GUI
  - panel
  - param
  - pyvista
  # IO
  - dxchange
  - jsonschema
  # -- Development
  # utils
  - pre-commit
  # packaging
  - anaconda-client
  - boa
  - conda-build < 4
  - conda-verify
  - python-build
  # doc
  - pydocstyle
  - sphinx
  - sphinx_rtd_theme
  # test
  - pytest
  - pytest-cov
  # pip
  - pip:
    - check-wheel-contents
    - pytest-playwright
    - bm3d-streak-removal
