package:
  name: imars3d
  version: 0.1.3

source:
  git_rev: next
  git_url: https://github.com/ornlneutronimaging/iMars3D

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - tomopy
    - numpy
    - pyyaml
    - scipy
    - matplotlib
    - mpi4py
    - psutil
    - scikit-image
    - dxchange
    - progressbar2

about:
  home: https://github.com/ornlneutronimaging/iMars3D
