name: imars3d_rtd
channels:
  - conda-forge
dependencies:
  - pip
  - astropy
  - tomopy
  - dxchange
  - jsonschema
  - pooch
  - panel
  - param
  - pyvista
  - holoviews
  - bokeh
  - datashader
  - hvplot
  - build
  - toml
  - pip:
    - versioningit
