# load information from setup.cfg/setup.py
{% set data = load_setup_py_data() %}
{% set license = data.get('license') %}
{% set description = data.get('description') %}
{% set url = data.get('url') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: imars3d
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: {{ version_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - build
    - toml
    - versioningit

  run:
    - astropy
    - tomopy
    - jsonschema
    - dxchange
    - olefile
    - pooch
    - panel
    - param
    - pyvista
    - holoviews
    - bokeh
    - datashader
    - hvplot

test:
  imports:
    - imars3d

about:
  home: {{ url }}
  license: {{ license }}
  license_family: BSD
  license_file: ../LICENSE
  summary: {{ description }}
