# this will reproduce the version from tags to match versioningit
{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}

package:
  name: imars3d
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  string: py{{py}}
  number: {{ version_number }}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit
    - pip

  build:
    - build
    - toml

  run:
    - astropy
    - tomopy
    - jsonschema
    - dxchange
    - pooch
    - panel
    - param
    - pyvista
    - holoviews
    - bokeh
    - datashader
    - hvplot

test:
  imports:
    - imars3d

about:
  home: https://github.com/ornlneutronimaging/iMars3D
  license: BSD (version 3)
  license_family: BSD
  license_file: ../LICENSE
