# this will reproduce the version from tags to match versioningit
{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
{% set version_number = '_' + version_number if version_number != '0' else '' %}

{% set version = version_tag + version_number %}

package:
  name: imars3d
  version: {{ version }}

source:
  path: ..

# source:
#   git_rev: next
#   git_url: https://github.com/ornlneutronimaging/iMars3D

build:
  noarch: python
# build:
#   noarch: python
#   string: py{{py}}
#   script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python

  run:
    - imars3d.backend
    - imars3d.ui


test:
  imports:
    - imars3d

about:
  home: https://github.com/ornlneutronimaging/iMars3D
  license: BSD (version 3)
  license_family: BSD
  license_file: ../LICENSE

outputs:
  - name: imars3d.backend
    source:
      path: ../imars3d/backend
    build:
      noarch: python
      string: py{{py}}
      script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    requirements:
      host:
        - python
        - versioningit

      build:
        - python
        - setuptools
        - astropy
        - tomopy
        - dxchange
        - pooch

      run:
        - python
        - tomopy
        - numpy
        - pyyaml
        - scipy
        - scikit-image
        - dxchange
        - tqdm

    test:
      imports:
        - imars3d
    # script: some_build_script.sh
  - name: imars3d.ui
    source:
        path: ../imars3d/ui
    build:
      noarch: python
      string: py{{py}}
      script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
    requirements:
      host:
        - python
        - versioningit

      build:
        - python
        - setuptools
        - astropy
        - tomopy
        - dxchange
        - pooch

      run:
        - python
        - tomopy
        - numpy
        - pyyaml
        - scipy
        - scikit-image
        - dxchange
        - tqdm
        - panel
        - param
        - pyvista
        - holoviews
        - bokeh
        - datashader
        - hvplot

    test:
      imports:
        - imars3d
    # script: some_other_build_script.sh
