# this will reproduce the version from tags to match versioningit
{% set version_tag = environ.get('GIT_DESCRIBE_TAG', '0.0.0') %}
{% set version_number = environ.get('GIT_DESCRIBE_NUMBER', '0') | string %}
{% set version_number = '_' + version_number if version_number != '0' else '' %}

{% set version = version_tag + version_number %}

package:
  name: "imars3d"
  version: {{ version }}

source:
  path: ..

# source:
#   git_rev: next
#   git_url: https://github.com/ornlneutronimaging/iMars3D


build:
  noarch: python
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - python
    - setuptools
    - astropy
    - tomopy
    - dxchange
    - pooch

  run:
    - python
    - tomopy
    - numpy
    - pyyaml
    - scipy
    - matplotlib
    - mpi4py
    - psutil
    - scikit-image
    - dxchange
    - progressbar2

test:
  imports:
    - imars3d

about:
  home: https://github.com/ornlneutronimaging/iMars3D
