# load information from setup.cfg/setup.py
{% set pyproject = load_file_data('pyproject.toml') %}
{% set project = pyproject.get('project', {}) %}
{% set license = project.get('license').get('text') %}
{% set description = project.get('description') %}
{% set project_url = pyproject.get('project', {}).get('urls') %}
{% set url = project_url.get('homepage') %}
# this will get the version set by environment variable
{% set version = environ.get('VERSION') %}
{% set version_number = version.split('+')[0] %}
{% set build_number = 0 %}

package:
  name: imars3d
  version: {{ version_number }}

source:
  path: ..

build:
  noarch: python
  number: {{ build_number }}
  string: py{{py}}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - versioningit

  build:
    - build
    - toml
    - versioningit

  run:
    - astropy
    - tomopy
    - jsonschema
    - dxchange
    - olefile
    - pooch
    - panel<1.3
    - param<2
    - pyvista
    - holoviews
    - bokeh
    - datashader
    - hvplot

test:
  imports:
    - imars3d

about:
  home: {{ url }}
  license: {{ license }}
  license_family: BSD
  license_file: ../LICENSE
  summary: {{ description }}
