name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: conda_environment.yml
      - name: Install testing requirements
        run: mamba env update --name test --file conda_development.yml
      - name: Install ui test requirements
        run: playwright install
      - name: Install iMars3d in editable mode
        run: pip install -e .
      - name: Unit test with code coverage
        run: |
          python -m pytest --cov --cov-report=xml --cov-report=term tests/unit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build-wheel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: conda_environment.yml
      - name: Build Wheel
        run: python -m build --no-isolation --wheel
      - name: Check Wheel Contents
        run: check-wheel-contents .

  build-conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: conda_environment.yml
      - name: Install testing requirements
        run: mamba env update --name test --file conda_development.yml
      - name: Build Conda Package
        run: |
          conda build --output-folder . -c conda-forge .
      - name: Verify Conda Package
        run: |
          conda verify noarch/imars3d*.tar.bz2

  trigger-deploy:
    runs-on: ubuntu-22.04
    needs: [linux, build-conda]
    # only trigger deploys from protected branches
    if: ${{ github.ref_protected || github.ref_type == 'tag' }}
    steps:
      - name: Determine Environment
        uses: neutrons/branch-mapper@main
        id: conda_env_name
        with:
          prefix: imars3d

      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 11848
          ref_name: main
          variables: |
            PLAY="update"
            CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

      - name: Annotate commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
