name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          miniforge-version: latest
          environment-file: environment.yml
          use-mamba: true
      - name: Verify docstrings
        run: pydocstyle --convention=numpy src/
      - name: Install ui test requirements
        run: playwright install
      - name: Install iMars3d in editable mode
        run: pip install -e .
      - name: Tests without data repository
        run: |
          python -m pytest --cov --cov-report=xml --cov-report=term -m "not datarepo"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  build-wheel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniforge-version: latest
          environment-file: environment.yml
      - name: Build Wheel
        run: python -m build --no-isolation --wheel
      - name: Check Wheel Contents
        run: check-wheel-contents .
