name: Install/Update Analysis Cluster
on:
  push:
    branches:
      - main
jobs:
  ornl-trigger-ansible:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 11848
          ref_name: main
          variables: |
            PLAY="update"
            CONDA_ENV="imars3d"
