name: Install/Update Analysis Cluster
on: 
  push:
    branches:
      - qa
jobs:
  ornl-trigger-ansible:
    runs-on: ubuntu-20.04
    steps:
      - run: curl -sX POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master -F "variables[PLAY]=conda/update" -F "variables[CONDA_ENV]=imars3d-qa" ${{ secrets.GITLAB_TRIGGER_URL }} > /dev/null
