name: protected-branches

on:
  workflow_dispatch:
  push:
    branches: [next, qa, main]

jobs:
  integration-tests:
    runs-on: cades
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          environment-file: conda_development.yml
          use-mamba: true
      - name: Add pending status
        uses: ouzi-dev/commit-status-updater@v2
        if: ${{ always() && github.event_name == 'workflow_dispatch' }}
      - name: Unit integration tests
        run: python -m pytest tests/integration
      - name: Update job status
        if: ${{ always() && github.event_name == 'workflow_dispatch' }}
        uses: ouzi-dev/commit-status-updater@v2
        with:
          status: "${{ job.status }}"

  build-conda:
    runs-on: ubuntu-latest
    needs: [integration-tests]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          mamba-version: "*"
          environment-file: conda_environment.yml
      - name: Install testing requirements
        run: mamba env update --name test --file conda_development.yml
      - name: Build Conda Package
        run: |
          conda build --output-folder . -c conda-forge .
      - name: Verify Conda Package
        run: |
          conda verify noarch/imars3d*.tar.bz2

  trigger-deploy:
    runs-on: ubuntu-22.04
    needs: [build-conda]
    # only trigger deploys from protected branches
    if: ${{ github.ref_protected || github.ref_type == 'tag' }}
    steps:
      - name: Determine Environment
        uses: neutrons/branch-mapper@main
        id: conda_env_name
        with:
          prefix: imars3d

      - name: Trigger deploy
        id: trigger
        uses: eic/trigger-gitlab-ci@v2
        with:
          url: https://code.ornl.gov
          token: ${{ secrets.GITLAB_TRIGGER_TOKEN }}
          project_id: 11848
          ref_name: main
          variables: |
            PLAY="update"
            CONDA_ENV="${{ steps.conda_env_name.outputs.name }}"

      - name: Annotate commit
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            GitLab pipeline for ${{ steps.conda_env_name.outputs.name }} has been submitted for this commit: ${{ steps.trigger.outputs.web_url }}
