name: unit-test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [next, qa, main]

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: conda_environment.yml
    - name: Install testing requirements
      run: mamba env update --name test --file conda_development.yml
    - name: Install iMars3d in editable mode
      run: pip install -e .
    - name: Unit test with code coverage
      run: |
        python -m pytest --cov --cov-report=xml --cov-report=term tests/unit
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
  build-wheel:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        mamba-version: "*"
        environment-file: conda_environment.yml
    - name: Install Wheel
      run: python -m build --no-isolation --wheel
    - name: Check Wheel Contents
      run: check-wheel-contents .
